# Tuples are immutable, so their items cannot be changed after creation.
# Parallel data structures are a historic way to group related data and are
# useful in teaching, but we will learn better ways to organize this data.

# states = (
#     "Alabama",
#     "Alaska",
#     "Arizona",
#     "Arkansas",
#     "California",
#     "Colorado",
#     "Connecticut",
#     "Delaware",
#     "Florida",
#     "Georgia",
#     "Hawaii",
#     "Idaho",
#     "Illinois",
#     "Indiana",
#     "Iowa",
#     "Kansas",
#     "Kentucky",
#     "Louisiana",
#     "Maine",
#     "Maryland",
#     "Massachusetts",
#     "Michigan",
#     "Minnesota",
#     "Mississippi",
#     "Missouri",
#     "Montana",
#     "Nebraska",
#     "Nevada",
#     "New Hampshire",
#     "New Jersey",
#     "New Mexico",
#     "New York",
#     "North Carolina",
#     "North Dakota",
#     "Ohio",
#     "Oklahoma",
#     "Oregon",
#     "Pennsylvania",
#     "Rhode Island",
#     "South Carolina",
#     "South Dakota",
#     "Tennessee",
#     "Texas",
#     "Utah",
#     "Vermont",
#     "Virginia",
#     "Washington",
#     "West Virginia",
#     "Wisconsin",
#     "Wyoming",
# )

# state_capitals = (
#     "Montgomery",
#     "Juneau",
#     "Phoenix",
#     "Little Rock",
#     "Sacramento",
#     "Denver",
#     "Hartford",
#     "Dover",
#     "Tallahassee",
#     "Atlanta",
#     "Honolulu",
#     "Boise",
#     "Springfield",
#     "Indianapolis",
#     "Des Moines",
#     "Topeka",
#     "Frankfort",
#     "Baton Rouge",
#     "Augusta",
#     "Annapolis",
#     "Boston",
#     "Lansing",
#     "Saint Paul",
#     "Jackson",
#     "Jefferson City",
#     "Helena",
#     "Lincoln",
#     "Carson City",
#     "Concord",
#     "Trenton",
#     "Santa Fe",
#     "Albany",
#     "Raleigh",
#     "Bismarck",
#     "Columbus",
#     "Oklahoma City",
#     "Salem",
#     "Harrisburg",
#     "Providence",
#     "Columbia",
#     "Pierre",
#     "Nashville",
#     "Austin",
#     "Salt Lake City",
#     "Montpelier",
#     "Richmond",
#     "Olympia",
#     "Charleston",
#     "Madison",
#     "Cheyenne",
# )

# states_and_capitals = (
#     ("Alabama", "Montgomery"),
#     ("Alaska", "Juneau"),
#     ("Arizona", "Phoenix"),
#     ("Arkansas", "Little Rock"),
#     ("California", "Sacramento"),
#     ("Colorado", "Denver"),
#     ("Connecticut", "Hartford"),
#     ("Delaware", "Dover"),
#     ("Florida", "Tallahassee"),
#     ("Georgia", "Atlanta"),
#     ("Hawaii", "Honolulu"),
#     ("Idaho", "Boise"),
#     ("Illinois", "Springfield"),
#     ("Indiana", "Indianapolis"),
#     ("Iowa", "Des Moines"),
#     ("Kansas", "Topeka"),
#     ("Kentucky", "Frankfort"),
#     ("Louisiana", "Baton Rouge"),
#     ("Maine", "Augusta"),
#     ("Maryland", "Annapolis"),
#     ("Massachusetts", "Boston"),
#     ("Michigan", "Lansing"),
#     ("Minnesota", "Saint Paul"),
#     ("Mississippi", "Jackson"),
#     ("Missouri", "Jefferson City"),
#     ("Montana", "Helena"),
#     ("Nebraska", "Lincoln"),
#     ("Nevada", "Carson City"),
#     ("New Hampshire", "Concord"),
#     ("New Jersey", "Trenton"),
#     ("New Mexico", "Santa Fe"),
#     ("New York", "Albany"),
#     ("North Carolina", "Raleigh"),
#     ("North Dakota", "Bismarck"),
#     ("Ohio", "Columbus"),
#     ("Oklahoma", "Oklahoma City"),
#     ("Oregon", "Salem"),
#     ("Pennsylvania", "Harrisburg"),
#     ("Rhode Island", "Providence"),
#     ("South Carolina", "Columbia"),
#     ("South Dakota", "Pierre"),
#     ("Tennessee", "Nashville"),
#     ("Texas", "Austin"),
#     ("Utah", "Salt Lake City"),
#     ("Vermont", "Montpelier"),
#     ("Virginia", "Richmond"),
#     ("Washington", "Olympia"),
#     ("West Virginia", "Charleston"),
#     ("Wisconsin", "Madison"),
#     ("Wyoming", "Cheyenne"),
# )


# states_capitals_birds = (
#     ("Alabama", "Montgomery", "Yellowhammer"),
#     ("Alaska", "Juneau", "Willow Ptarmigan"),
#     ("Arizona", "Phoenix", "Cactus Wren"),
#     ("Arkansas", "Little Rock", "Northern Mockingbird"),
#     ("California", "Sacramento", "California Quail"),
#     ("Colorado", "Denver", "Lark Bunting"),
#     ("Connecticut", "Hartford", "American Robin"),
#     ("Delaware", "Dover", "Blue Hen Chicken"),
#     ("Florida", "Tallahassee", "Northern Mockingbird"),
#     ("Georgia", "Atlanta", "Brown Thrasher"),
#     ("Hawaii", "Honolulu", "Nene"),
#     ("Idaho", "Boise", "Mountain Bluebird"),
#     ("Illinois", "Springfield", "Northern Cardinal"),
#     ("Indiana", "Indianapolis", "Northern Cardinal"),
#     ("Iowa", "Des Moines", "Eastern Goldfinch"),
#     ("Kansas", "Topeka", "Western Meadowlark"),
#     ("Kentucky", "Frankfort", "Northern Cardinal"),
#     ("Louisiana", "Baton Rouge", "Brown Pelican"),
#     ("Maine", "Augusta", "Black-capped Chickadee"),
#     ("Maryland", "Annapolis", "Baltimore Oriole"),
#     ("Massachusetts", "Boston", "Black-capped Chickadee"),
#     ("Michigan", "Lansing", "American Robin"),
#     ("Minnesota", "Saint Paul", "Common Loon"),
#     ("Mississippi", "Jackson", "Northern Mockingbird"),
#     ("Missouri", "Jefferson City", "Eastern Bluebird"),
#     ("Montana", "Helena", "Western Meadowlark"),
#     ("Nebraska", "Lincoln", "Western Meadowlark"),
#     ("Nevada", "Carson City", "Mountain Bluebird"),
#     ("New Hampshire", "Concord", "Purple Finch"),
#     ("New Jersey", "Trenton", "Eastern Goldfinch"),
#     ("New Mexico", "Santa Fe", "Greater Roadrunner"),
#     ("New York", "Albany", "Eastern Bluebird"),
#     ("North Carolina", "Raleigh", "Northern Cardinal"),
#     ("North Dakota", "Bismarck", "Western Meadowlark"),
#     ("Ohio", "Columbus", "Northern Cardinal"),
#     ("Oklahoma", "Oklahoma City", "Scissor-tailed Flycatcher"),
#     ("Oregon", "Salem", "Western Meadowlark"),
#     ("Pennsylvania", "Harrisburg", "Ruffed Grouse"),
#     ("Rhode Island", "Providence", "Rhode Island Red"),
#     ("South Carolina", "Columbia", "Carolina Wren"),
#     ("South Dakota", "Pierre", "Ring-necked Pheasant"),
#     ("Tennessee", "Nashville", "Northern Mockingbird"),
#     ("Texas", "Austin", "Northern Mockingbird"),
#     ("Utah", "Salt Lake City", "California Gull"),
#     ("Vermont", "Montpelier", "Hermit Thrush"),
#     ("Virginia", "Richmond", "Northern Cardinal"),
#     ("Washington", "Olympia", "American Goldfinch"),
#     ("West Virginia", "Charleston", "Northern Cardinal"),
#     ("Wisconsin", "Madison", "American Robin"),
#     ("Wyoming", "Cheyenne", "Western Meadowlark"),
# )


# # my_state = states.sort()

# # for index in range(0, len(states)):
# #     print(f"{states[index]}, {state_capitals[index]}")

# # selects the state Illinois in the first [#] while the second [#] holds the capital
# print(f"{states_and_capitals[12][0]}")
# print(f"{states_and_capitals[12][1]}")


# Constants vs tuples

SCHOOL_NAME = ("Mchenry County College",)
print(SCHOOL_NAME)

# replaces does not modify (same as string)
SCHOOL_NAME = "Elgin Community College"
print(SCHOOL_NAME)

# NOT allowed
# SCHOOL_NAME.pop()

print(len(SCHOOL_NAME))
